

export enum View {
  DASHBOARD = 'DASHBOARD',
  ADVISOR = 'ADVISOR',
  WEEKLY_TIPS = 'WEEKLY_TIPS',
  BEST_PRACTICES = 'BEST_PRACTICES',
  TRAINING = 'TRAINING',
  REPORT_ANALYZER = 'REPORT_ANALYZER',
  TOOLKIT = 'TOOLKIT',
  NEWS_BLOG = 'NEWS_BLOG'
}

export interface NewsItem {
  id: string;
  headline: string;
  category: 'Operational' | 'Policy' | 'Certification' | 'Training' | 'Trend' | 'Risk';
  source: string;
  summary: string;
  date: string;
  link: string;
  sources?: Array<{ title: string; url: string }>;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
  isError?: boolean;
  sources?: Array<{ title: string; url: string }>;
  isPinned?: boolean;
}

export interface BestPracticeItem {
  title: string;
  summary: string;
  source: string;
  date: string;
}

export interface TrainingModule {
  targetAudience: string;
  topic: string;
  content: string;
  generatedDate: string;
}

export interface StoredTrainingModule extends TrainingModule {
  id: string;
  timestamp: number;
}

export interface Template {
  id: string;
  title: string;
  description: string;
  content: string;
}

export interface StoredReport {
  id: string;
  timestamp: number;
  dateStr: string;
  content: string;
  analysis: string;
}

export interface WeeklyTip {
  id: string;
  weekDate: string;
  topic: string;
  content: string;
  isAutoGenerated: boolean;
  timestamp: number;
}

export interface UserProfile {
  name: string;
  phoneNumber: string; // International format for WhatsApp
  email: string;
  preferredChannel: 'WhatsApp' | 'Email';
}

export interface KnowledgeDocument {
  id: string;
  title: string;
  content: string;
  dateAdded: string;
}

export interface SavedTrend {
  id: string;
  topic: string;
  timestamp: number;
}

export enum SecurityRole {
  GUARD = 'Security Guard',
  SUPERVISOR = 'Site Supervisor',
  GEN_SUPERVISOR = 'General Supervisor'
}
